# Workflow 1
# This workflow was created from the Java gradle Build
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# Then tests the contents

name: Java CI with Gradle Workflow 1

on:
  branch_protection_rule:
    types: [edited, created, deleted]
  schedule:
  - cron:  '30 16 * * 5'    # Every Friday at 8:30am
        
jobs:
  gradle:
    strategy:
      
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build Workflow 1
      run: gradle build
      
    - name: Execute Gradle test Workflow 1
      run: gradle test
