# Workflow 2
# This workflow was create dusing the Github Actions: Java with Gradle
# This workflow will build and test a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# This workflow also includes an Experimental Include and will fail safely in case there is an error. 
#second workflow: approve, review

name: Java CI with Gradle Workflow 2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
        
jobs:
  gradle:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        experimental: [false]
        include:
          - java: 8
            os: ubuntu-18.04
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build Workflow 2
      run: gradle build
      
    - name: Execute Gradle test Workflow 2
      run: gradle test
