# Workflow 3
# Created using Github Actions
# Triggered by a Push or Pull Request to Main branch. As well as any open PR's
# Uses "triage" command to triage if and only if the Pull Request user is not a bot

name: Java CI with Gradle Workflow 3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - opened

jobs:
  triage:
    if: >-
      github.event.pull_request.user.login != 'octobot' &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        java: [11, 17]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        
    - name: Build with Gradle Workflow 3
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        gradle-version: 7.4
        arguments: build
    - name: Test with Gradle Workflow 3
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: test


